name: "RHVoice"
description: "RHVoice - a local text-to-speech engine"
version: "1.0.3"
slug: "rhvoice"
init: false
arch:
  - aarch64
  - amd64
image: definitio/ha-rhvoice-addon-{arch}
ports:
  8080/tcp: 8080
